// skool-web/src/routes/login/+page.svelte
<script lang="ts">
	import Button from "$lib/components/Button.svelte";

  const loggingIn = false;

  const handleSubmit: svelte.JSX.EventHandler<SubmitEvent, HTMLFormElement> = ({target}) => {
    const data = new FormData(target as any);

    const username = data.get("username");
    const password = data.get("password");

    console.log(username, password);
}
</script>

<div class="root">
	<div class="card">
		<h1>Logga in</h1>
		<p>Dina inloggningsuppgifter krypteras och sparas bara på den här enheten. Var försiktig!</p>
		<form on:submit|preventDefault={handleSubmit}>
			<label for="username">Användarnamn</label>
			<input id="username" name="username" placeholder="ab12345" />

			<label for="password">Lösenord</label>
			<input id="password" name="password" type="password" />

			<Button type="submit" disabled={loggingIn}>
				{loggingIn ? "Loggar in ..." : "Logga in"}
			</Button>
		</form>
	</div>
</div>

<style>
	.root {
		display: flex;
		flex-direction: column;
		align-items: center;
		min-height: calc(100vh - var(--header-height));
	}

	.card {
		padding: 0 var(--page-gutter);
		margin: calc(var(--header-height) + var(--page-gutter)) 0;
		text-align: center;
	}

	@media (min-width: 480px) {
		.root {
			background-color: var(--background-secondary);
			justify-content: center;
		}

		.card {
			padding: var(--page-gutter);
			width: 400px;
			border-radius: 12px;
			box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.1);
			background-color: var(--background-primary);
		}
	}

	h1 {
		font-size: 2rem;
		font-weight: 500;
		letter-spacing: -0.025em;
		margin: 1rem 0;
	}

	p {
		color: var(--text-muted);
		font-size: 0.875rem;
		line-height: 1.5;
		letter-spacing: -0.006em;
		margin: 1rem 0;
		font-weight: 400;
	}

  form {
    text-align: start;
  }

  input {
		height: 3rem;
		border: 1px solid #eee;
		border-radius: 4px;
		width: 100%;
		margin-top: 0.5rem;
		margin-bottom: 24px;
		box-sizing: border-box;
		padding-inline: 8px;
		font-family: var(--font-main);
		font-size: 14px;
  }

		input::placeholder {
			color: #aaa;
			opacity: 1;
  }

  input:focus {
    outline: var(--brand-primary) solid 2px;
  }

  label {
		font-family: var(--font-main);
		font-size: 14px;
		font-weight: 500;
  }
</style>

// skool-web/pages/login.tsx
import { Field, Form, Formik } from "formik";
import { useAuth } from "../lib/auth";
import { NextPage } from "next";
import { useRouter } from "next/router";
import { useEffect } from "react";
import Layout from "../components/layout/layout";
import styles from "./login.module.scss";

const LoginPage: NextPage = () => {
  const { login, authenticated, loggingIn } = useAuth();
  const router = useRouter();
  const redirect = router.query.redirect?.toString() || "/"; // callback url

  useEffect(() => {
    if (authenticated) {
      router.push(redirect);
    }
  }, [authenticated, redirect, router]);

  return (
    <Layout navbar={false}>
      <div className="root">
        <div className="card">
          <h1>Logga in</h1>
          <p>
            Dina inloggningsuppgifter krypteras och sparas bara på den här
            enheten. Var försiktig!
          </p>
          <Formik
            initialValues={{ username: "", password: "" }}
            onSubmit={({ username, password }, { setStatus }) => {
              setStatus();
              login(username, password).catch((e) => setStatus(e.toString()));
            }}
          >
            {({ status }) => (
              <Form className={styles.form}>
                <label htmlFor="username">Användarnamn</label>
                <Field id="username" name="username" placeholder="ab12345" />

                <label htmlFor="password">Lösenord</label>
                <Field id="password" name="password" type="password" />

                <div>{status}</div>

                <button type="submit" disabled={loggingIn}>
                  {loggingIn ? "Loggar in ..." : "Logga in"}
                </button>
              </Form>
            )}
          </Formik>
        </div>
      </div>
      <style jsx>{`
        .root {
          display: flex;
          flex-direction: column;
          align-items: center;
          min-height: 100vh;
        }

        .card {
          padding: 0 var(--page-gutter);
          margin: calc(var(--navbar-height) + var(--page-gutter)) 0;
        }

        h1 {
          font-size: 32px;
          font-weight: 500;
          letter-spacing: -0.025em;
          margin: 16px 0;
        }

        p {
          color: var(--text-muted);
          font-size: 14px;
          line-height: 1.5;
          letter-spacing: -0.006em;
          margin: 16px 0;
          font-weight: 400;
        }

        h1,
        p {
          text-align: center;
        }

        button {
          background-color: var(--brand-primary);
          color: #fff;
          border: 0;
          font-family: var(--font-main);
          border-radius: 4px;
          width: 100%;
          height: 48px;
          font-size: 14px;
          line-height: 1;
          cursor: pointer;
          transition: all 0.1s;
        }

        button:hover {
          background-color: var(--brand-primary-dark);
        }

        button:disabled {
          opacity: 0.1;
          cursor: default;
        }

        @media (min-width: 480px) {
          .root {
            background-color: var(--background-secondary);
            justify-content: center;
          }

          .card {
            padding: var(--page-gutter);
            width: 400px;
            border-radius: 12px;
            box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.1);
            background-color: var(--background-primary);
          }
        }
      `}</style>
    </Layout>
  );
};

export default LoginPage;
